# 02-3. Softmax Classifier

- 100마리에 동물에 대한 16개의 feature

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
data = np.loadtxt('data/data-04-zoo.csv', delimiter=',',
                 dtype=np.float32)

x_data = data[:, :-1]
y_data = data[:, [-1]]

In [3]:
print(x_data.shape)
print(y_data.shape)

# DV가 가지는 카테고리
nb_classes = 7
# IV의 feature 개수
feature_num = x_data.shape[1]

(101, 16)
(101, 1)


In [4]:
# 7개의 카테고리를 가지는 DV(y_data)와 카테고리수를 넣어 one-hot encoding
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
y_one_hot[:5]

array([[1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.]], dtype=float32)

- 다중 분류(softmax)에서 제일 먼저 DV의 값을 확인
- 레이블로 되어있다면 one-hot-encoding으로 0/1 값으로 변환
- 원-핫 인코딩을 하는 이유
    - 정답을 각각의 레이블 확률로 표현하기 위해 (e.g. 0.1, 0.1, 0.7, 0.05, 0.05, ..)

In [5]:
model = tf.keras.Sequential()

In [6]:
# 입력 데이터 16개, 출력 데이터 7개
model.add(tf.keras.layers.Dense(units=nb_classes,  # 출력값의 개수
                                input_dim=feature_num
                                 # activation='softmax'   # 아래 코드 대신 작성하는 방법
                               ))
# 다중분류에서 활성화 함수: softmax
# cf> 선형회귀: 'linear', 로지스틱:'sigmoid'
model.add(tf.keras.layers.Activation('softmax'))

In [7]:
model.compile(loss='categorical_crossentropy',  # 손실함수- 다중분류: categorical_crossentropy Error (CEE)
                                                # cross-entropy error: 모델이 예측한 확률값과 정답 데이터의 확률값의 분포(각 레이블 값과 예측한 확률값의 차이)에 대한 오차 계산
                                                #                      이 오차가 최소화가 될 때의 w와 b값을 찾는 것
                                                # cf> 선형회귀: MSE (선형함수에만 적용 가능)
                                                #     로지스틱: binary_crossentropy
              optimizer=tf.keras.optimizers.SGD(learning_rate=0.1),
              # 경사하강법의 learning_rate을 0.01로 할 경우 optimizer='sgd'
              metrics=['accuracy']
             )

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 119       
_________________________________________________________________
activation (Activation)      (None, 7)                 0         
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


- Param (파라미터의 수) >> `119`개 (회귀계수와 bias의 수)
- IV개수 16개 X DV 7개 + bias 7개 = 119개

In [9]:
loss = model.fit(x_data,
                 y_one_hot,
                 epochs=1000)

Epoch 1/1000
4/4 [==============================] - 0s 625us/step - loss: 2.0084 - accuracy: 0.1881
Epoch 2/1000
4/4 [==============================] - 0s 583us/step - loss: 1.1980 - accuracy: 0.6634
Epoch 3/1000
4/4 [==============================] - 0s 262us/step - loss: 1.0636 - accuracy: 0.7525
Epoch 4/1000
4/4 [==============================] - 0s 299us/step - loss: 0.9673 - accuracy: 0.7822
Epoch 5/1000
4/4 [==============================] - 0s 680us/step - loss: 0.8899 - accuracy: 0.8317
Epoch 6/1000
4/4 [==============================] - 0s 534us/step - loss: 0.8417 - accuracy: 0.8416
Epoch 7/1000
4/4 [==============================] - 0s 548us/step - loss: 0.8017 - accuracy: 0.8614
Epoch 8/1000
4/4 [==============================] - 0s 518us/step - loss: 0.7601 - accuracy: 0.8614
Epoch 9/1000
4/4 [==============================] - 0s 861us/step - loss: 0.7319 - accuracy: 0.8614
Epoch 10/1000
4/4 [==============================] - 0s 601us/step - loss: 0.6990 - accuracy: 0.8614

4/4 [==============================] - 0s 529us/step - loss: 0.2482 - accuracy: 0.9505
Epoch 83/1000
4/4 [==============================] - 0s 662us/step - loss: 0.2435 - accuracy: 0.9505
Epoch 84/1000
4/4 [==============================] - 0s 538us/step - loss: 0.2423 - accuracy: 0.9505
Epoch 85/1000
4/4 [==============================] - 0s 333us/step - loss: 0.2378 - accuracy: 0.9505
Epoch 86/1000
4/4 [==============================] - 0s 333us/step - loss: 0.2420 - accuracy: 0.9604
Epoch 87/1000
4/4 [==============================] - 0s 544us/step - loss: 0.2354 - accuracy: 0.9604
Epoch 88/1000
4/4 [==============================] - 0s 543us/step - loss: 0.2326 - accuracy: 0.9604
Epoch 89/1000
4/4 [==============================] - 0s 277us/step - loss: 0.2311 - accuracy: 0.9505
Epoch 90/1000
4/4 [==============================] - 0s 571us/step - loss: 0.2293 - accuracy: 0.9505
Epoch 91/1000
4/4 [==============================] - 0s 529us/step - loss: 0.2303 - accuracy: 0.9604
Epoc

4/4 [==============================] - 0s 514us/step - loss: 0.1479 - accuracy: 0.9703
Epoch 163/1000
4/4 [==============================] - 0s 323us/step - loss: 0.1473 - accuracy: 0.9703
Epoch 164/1000
4/4 [==============================] - 0s 499us/step - loss: 0.1465 - accuracy: 0.9802
Epoch 165/1000
4/4 [==============================] - 0s 511us/step - loss: 0.1454 - accuracy: 0.9802
Epoch 166/1000
4/4 [==============================] - 0s 303us/step - loss: 0.1454 - accuracy: 0.9802
Epoch 167/1000
4/4 [==============================] - 0s 574us/step - loss: 0.1442 - accuracy: 0.9802
Epoch 168/1000
4/4 [==============================] - 0s 626us/step - loss: 0.1435 - accuracy: 0.9802
Epoch 169/1000
4/4 [==============================] - 0s 586us/step - loss: 0.1423 - accuracy: 0.9802
Epoch 170/1000
4/4 [==============================] - 0s 324us/step - loss: 0.1415 - accuracy: 0.9802
Epoch 171/1000
4/4 [==============================] - 0s 560us/step - loss: 0.1422 - accuracy: 0.

4/4 [==============================] - 0s 600us/step - loss: 0.1060 - accuracy: 1.0000
Epoch 243/1000
4/4 [==============================] - 0s 564us/step - loss: 0.1061 - accuracy: 1.0000
Epoch 244/1000
4/4 [==============================] - 0s 365us/step - loss: 0.1059 - accuracy: 1.0000
Epoch 245/1000
4/4 [==============================] - 0s 569us/step - loss: 0.1060 - accuracy: 1.0000
Epoch 246/1000
4/4 [==============================] - 0s 588us/step - loss: 0.1098 - accuracy: 1.0000
Epoch 247/1000
4/4 [==============================] - 0s 605us/step - loss: 0.1041 - accuracy: 1.0000
Epoch 248/1000
4/4 [==============================] - 0s 597us/step - loss: 0.1037 - accuracy: 1.0000
Epoch 249/1000
4/4 [==============================] - 0s 263us/step - loss: 0.1037 - accuracy: 1.0000
Epoch 250/1000
4/4 [==============================] - 0s 524us/step - loss: 0.1024 - accuracy: 1.0000
Epoch 251/1000
4/4 [==============================] - 0s 720us/step - loss: 0.1040 - accuracy: 1.

4/4 [==============================] - 0s 556us/step - loss: 0.0845 - accuracy: 1.0000
Epoch 323/1000
4/4 [==============================] - 0s 531us/step - loss: 0.0828 - accuracy: 1.0000
Epoch 324/1000
4/4 [==============================] - 0s 554us/step - loss: 0.0829 - accuracy: 1.0000
Epoch 325/1000
4/4 [==============================] - 0s 558us/step - loss: 0.0825 - accuracy: 1.0000
Epoch 326/1000
4/4 [==============================] - 0s 569us/step - loss: 0.0822 - accuracy: 1.0000
Epoch 327/1000
4/4 [==============================] - 0s 513us/step - loss: 0.0822 - accuracy: 1.0000
Epoch 328/1000
4/4 [==============================] - 0s 336us/step - loss: 0.0817 - accuracy: 1.0000
Epoch 329/1000
4/4 [==============================] - 0s 531us/step - loss: 0.0824 - accuracy: 1.0000
Epoch 330/1000
4/4 [==============================] - 0s 279us/step - loss: 0.0826 - accuracy: 0.9901
Epoch 331/1000
4/4 [==============================] - 0s 253us/step - loss: 0.0818 - accuracy: 1.

4/4 [==============================] - 0s 605us/step - loss: 0.0690 - accuracy: 1.0000
Epoch 403/1000
4/4 [==============================] - 0s 256us/step - loss: 0.0688 - accuracy: 1.0000
Epoch 404/1000
4/4 [==============================] - 0s 291us/step - loss: 0.0683 - accuracy: 1.0000
Epoch 405/1000
4/4 [==============================] - 0s 605us/step - loss: 0.0683 - accuracy: 1.0000
Epoch 406/1000
4/4 [==============================] - 0s 590us/step - loss: 0.0680 - accuracy: 1.0000
Epoch 407/1000
4/4 [==============================] - 0s 572us/step - loss: 0.0678 - accuracy: 1.0000
Epoch 408/1000
4/4 [==============================] - 0s 587us/step - loss: 0.0674 - accuracy: 1.0000
Epoch 409/1000
4/4 [==============================] - 0s 271us/step - loss: 0.0679 - accuracy: 1.0000
Epoch 410/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0678 - accuracy: 1.0000
Epoch 411/1000
4/4 [==============================] - 0s 288us/step - loss: 0.0673 - accuracy: 1.

4/4 [==============================] - 0s 624us/step - loss: 0.0583 - accuracy: 1.0000
Epoch 483/1000
4/4 [==============================] - 0s 619us/step - loss: 0.0580 - accuracy: 1.0000
Epoch 484/1000
4/4 [==============================] - 0s 347us/step - loss: 0.0580 - accuracy: 1.0000
Epoch 485/1000
4/4 [==============================] - 0s 271us/step - loss: 0.0584 - accuracy: 1.0000
Epoch 486/1000
4/4 [==============================] - 0s 556us/step - loss: 0.0582 - accuracy: 1.0000
Epoch 487/1000
4/4 [==============================] - 0s 599us/step - loss: 0.0574 - accuracy: 1.0000
Epoch 488/1000
4/4 [==============================] - 0s 501us/step - loss: 0.0575 - accuracy: 1.0000
Epoch 489/1000
4/4 [==============================] - 0s 521us/step - loss: 0.0574 - accuracy: 1.0000
Epoch 490/1000
4/4 [==============================] - 0s 523us/step - loss: 0.0572 - accuracy: 1.0000
Epoch 491/1000
4/4 [==============================] - 0s 800us/step - loss: 0.0575 - accuracy: 1.

4/4 [==============================] - 0s 600us/step - loss: 0.0504 - accuracy: 1.0000
Epoch 563/1000
4/4 [==============================] - 0s 308us/step - loss: 0.0503 - accuracy: 1.0000
Epoch 564/1000
4/4 [==============================] - 0s 249us/step - loss: 0.0503 - accuracy: 1.0000
Epoch 565/1000
4/4 [==============================] - 0s 514us/step - loss: 0.0501 - accuracy: 1.0000
Epoch 566/1000
4/4 [==============================] - 0s 535us/step - loss: 0.0499 - accuracy: 1.0000
Epoch 567/1000
4/4 [==============================] - 0s 523us/step - loss: 0.0497 - accuracy: 1.0000
Epoch 568/1000
4/4 [==============================] - 0s 506us/step - loss: 0.0501 - accuracy: 1.0000
Epoch 569/1000
4/4 [==============================] - 0s 605us/step - loss: 0.0499 - accuracy: 1.0000
Epoch 570/1000
4/4 [==============================] - 0s 525us/step - loss: 0.0494 - accuracy: 1.0000
Epoch 571/1000
4/4 [==============================] - 0s 282us/step - loss: 0.0495 - accuracy: 1.

4/4 [==============================] - 0s 575us/step - loss: 0.0450 - accuracy: 1.0000
Epoch 643/1000
4/4 [==============================] - 0s 533us/step - loss: 0.0446 - accuracy: 1.0000
Epoch 644/1000
4/4 [==============================] - 0s 274us/step - loss: 0.0443 - accuracy: 1.0000
Epoch 645/1000
4/4 [==============================] - 0s 264us/step - loss: 0.0441 - accuracy: 1.0000
Epoch 646/1000
4/4 [==============================] - 0s 512us/step - loss: 0.0442 - accuracy: 1.0000
Epoch 647/1000
4/4 [==============================] - 0s 610us/step - loss: 0.0438 - accuracy: 1.0000
Epoch 648/1000
4/4 [==============================] - 0s 584us/step - loss: 0.0439 - accuracy: 1.0000
Epoch 649/1000
4/4 [==============================] - 0s 554us/step - loss: 0.0439 - accuracy: 1.0000
Epoch 650/1000
4/4 [==============================] - 0s 541us/step - loss: 0.0445 - accuracy: 1.0000
Epoch 651/1000
4/4 [==============================] - 0s 508us/step - loss: 0.0438 - accuracy: 1.

4/4 [==============================] - 0s 345us/step - loss: 0.0400 - accuracy: 1.0000
Epoch 723/1000
4/4 [==============================] - 0s 302us/step - loss: 0.0397 - accuracy: 1.0000
Epoch 724/1000
4/4 [==============================] - 0s 548us/step - loss: 0.0396 - accuracy: 1.0000
Epoch 725/1000
4/4 [==============================] - 0s 514us/step - loss: 0.0398 - accuracy: 1.0000
Epoch 726/1000
4/4 [==============================] - 0s 592us/step - loss: 0.0396 - accuracy: 1.0000
Epoch 727/1000
4/4 [==============================] - 0s 616us/step - loss: 0.0398 - accuracy: 1.0000
Epoch 728/1000
4/4 [==============================] - 0s 836us/step - loss: 0.0397 - accuracy: 1.0000
Epoch 729/1000
4/4 [==============================] - 0s 572us/step - loss: 0.0396 - accuracy: 1.0000
Epoch 730/1000
4/4 [==============================] - 0s 530us/step - loss: 0.0394 - accuracy: 1.0000
Epoch 731/1000
4/4 [==============================] - 0s 521us/step - loss: 0.0394 - accuracy: 1.

4/4 [==============================] - 0s 292us/step - loss: 0.0362 - accuracy: 1.0000
Epoch 803/1000
4/4 [==============================] - 0s 302us/step - loss: 0.0361 - accuracy: 1.0000
Epoch 804/1000
4/4 [==============================] - 0s 1ms/step - loss: 0.0362 - accuracy: 1.0000
Epoch 805/1000
4/4 [==============================] - 0s 533us/step - loss: 0.0361 - accuracy: 1.0000
Epoch 806/1000
4/4 [==============================] - 0s 559us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 807/1000
4/4 [==============================] - 0s 555us/step - loss: 0.0360 - accuracy: 1.0000
Epoch 808/1000
4/4 [==============================] - 0s 550us/step - loss: 0.0358 - accuracy: 1.0000
Epoch 809/1000
4/4 [==============================] - 0s 595us/step - loss: 0.0357 - accuracy: 1.0000
Epoch 810/1000
4/4 [==============================] - 0s 256us/step - loss: 0.0358 - accuracy: 1.0000
Epoch 811/1000
4/4 [==============================] - 0s 339us/step - loss: 0.0358 - accuracy: 1.00

4/4 [==============================] - 0s 310us/step - loss: 0.0331 - accuracy: 1.0000
Epoch 883/1000
4/4 [==============================] - 0s 628us/step - loss: 0.0331 - accuracy: 1.0000
Epoch 884/1000
4/4 [==============================] - 0s 819us/step - loss: 0.0332 - accuracy: 1.0000
Epoch 885/1000
4/4 [==============================] - 0s 554us/step - loss: 0.0331 - accuracy: 1.0000
Epoch 886/1000
4/4 [==============================] - 0s 308us/step - loss: 0.0332 - accuracy: 1.0000
Epoch 887/1000
4/4 [==============================] - 0s 503us/step - loss: 0.0330 - accuracy: 1.0000
Epoch 888/1000
4/4 [==============================] - 0s 820us/step - loss: 0.0329 - accuracy: 1.0000
Epoch 889/1000
4/4 [==============================] - 0s 550us/step - loss: 0.0329 - accuracy: 1.0000
Epoch 890/1000
4/4 [==============================] - 0s 327us/step - loss: 0.0327 - accuracy: 1.0000
Epoch 891/1000
4/4 [==============================] - 0s 505us/step - loss: 0.0328 - accuracy: 1.

4/4 [==============================] - 0s 498us/step - loss: 0.0305 - accuracy: 1.0000
Epoch 963/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 964/1000
4/4 [==============================] - 0s 498us/step - loss: 0.0303 - accuracy: 1.0000
Epoch 965/1000
4/4 [==============================] - 0s 249us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 966/1000
4/4 [==============================] - 0s 251us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 967/1000
4/4 [==============================] - 0s 249us/step - loss: 0.0305 - accuracy: 1.0000
Epoch 968/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 969/1000
4/4 [==============================] - 0s 500us/step - loss: 0.0303 - accuracy: 1.0000
Epoch 970/1000
4/4 [==============================] - 0s 249us/step - loss: 0.0304 - accuracy: 1.0000
Epoch 971/1000
4/4 [==============================] - 0s 499us/step - loss: 0.0302 - accuracy: 1.

In [10]:
# x_data의 70번째 값을 넣어 테스트 해보기
print(x_data[70])
pred = model.predict(x_data[[70]])
pred

[1. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 4. 1. 1. 1.]


array([[9.9921763e-01, 2.2896682e-05, 6.5159029e-04, 3.8706364e-07,
        7.8919875e-05, 2.7548673e-05, 1.0535617e-06]], dtype=float32)

In [11]:
# 예측 결과에서 가장 큰 값의 인덱스를 찾는 방법
pred.argmax(axis=1)

array([0], dtype=int64)